[package]
name = "gpu-primitive-canvas"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.83"
bytemuck = { version = "1.15.0", features = ["derive"] }
env_logger = "0.11.3"
pollster = "0.3.0"
wgpu = "0.20.0"
wgpu_text = "0.8.8"
winit = "0.30.0"
